### ISSUE TITLE
Unix epoch seconds

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sebbae/brackit#1]
Hi Sebastian,

I'm still using your awesome Ph.D. project for my own "playground" it seems :-)

As described here:
https://stackoverflow.com/questions/7482347/is-there-any-way-in-xquery-to-get-the-current-time-in-milliseconds-since-some-ep/7484211

I want to get the milliseconds since 1970-01-01.
(current-dateTime() - xs:dateTime("1970-01-01T00:00:00-00:00")) div xs:dayTimeDuration('PT0.001S')

Expected output would be an xs:integer/xs:long I guess as for instance with ExistDB: 
https://exist-db.org/exist/apps/eXide/index.html

The output however is a double, something along the lines: 1.474685673277E12

or as a function-parameter something like: 1474686553674 (casted to long/int64): Sat Sep 24 2016 03:09:13 and not end of April 2018.

I'm using it because I want to provide a simple function for opening a specific revision, which has been committed at the closest time to the given point in time:

```java
  @Override
  public Sequence execute(final StaticContext sctx, final QueryContext ctx, final Sequence[] args)
      throws QueryException {
    if (args.length < 3 || args.length > 4) {
      throw new QueryException(new QNm("No valid arguments specified!"));
    }
    final DBCollection col = (DBCollection) ctx.getStore().lookup(((Str) args[0]).stringValue());

    if (col == null) {
      throw new QueryException(new QNm("No valid arguments specified!"));
    }

    final String expResName = ((Str) args[1]).stringValue();
    final long time =
        FunUtil.getLong(args, 2, "pointInTime", System.currentTimeMillis(), null, true);
    final Instant pointInTime = Instant.ofEpochMilli(time);
    final boolean updatable = FunUtil.getBoolean(args, 3, "updatable", false, false);

    return col.getDocument(pointInTime, expResName, updatable);
  }
```

**Comment by sebbae** [comment]
Hi Johannes,

awesome to hear that you're still using it after all these years. ;-)

I looked into it and found that there was indeed a wrong computation rule and result type used for durations (xs:double instead of xs:decimal). Along with this I also found some timezones issues.

Thanks, for triggering me with this to spend some time again with brackit. It felt like home to get back to the code base again after almost 6 years now without having really touched it. Yay! :-D

BR,
Sebastian

**Comment by JohannesLichtenberger** [comment]
Ha, pretty cool, thanks :-)

I should make a pull request with my changes one day (added support for temporal collections/resources and fixed a few minor bugs) and tried to make it generic 6 years ago or so (plus added these temporal XPath axis extensions. However, now I'd probably change a few things.

It's however a shame that maybe noone uses Brackit (and also not my open source project ;-)), because it's an awesome idea and I think all the NoSQL DBSs are still lacking a proper query language.
