### ISSUE TITLE
Rewrite rules for indexes

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sebbae/brackit#3]
Hi Sebastian, if you ever look at this (last time it was incredibly fast ;)), can you give me some tips how to implement rewrite rules for index accesses? :-) I think I asked like 6 years ago, but couldn't find the mails, maybe I've used my university email address back then.

And regarding the usage of JSON,  maybe in the near future I'd have to make an interface for providing my own implementation of arrays and objects (but that should be relatively easy).

**Comment by sebbae** [comment]
Hi,

The optimization process is currently a predefined sequence of transformations and there are already some basic structures in the code that should help you getting started.

Generally, the query optimization rules are organized in stages, i.e. where currently each stage consists of a set of coherent rewrite rules or transformations of the AST. 

Additional stages can be plugged in easily. For example, sophisticated cost-based optimization as you find it typically in relational DB's could be introduced fully decoupled in it's own stage at any time.

As there are plenty of types of indexes possible and various situations in which you might want to apply an index - if a matching one exists - you should implement your own `org.brackit.xquery.compiler.optimizer.Stage`(s) for traversing the AST and searching for index-relevant patterns. 

Your rewrite rules will then have to alter the AST accordingly for index access by introducing their own types of AST nodes, e.g. nodes like AST(XQExt.MyIndexAccessExpr, indexId) or so. Accordingly, you will then need a respective counterpart in the following translation process to translate the new index access AST nodes into an executable form.

I suggest you have a look at the compilation brackitdb to get the idea of how to extend the core brackit compilation process itself. It even has a no-op IndexMatching stage for future me already. ;-)

The relevant starting points are `org.brackit.server.xquery.compiler.optimizer.DBCompiler`, `org.brackit.server.xquery.compiler.optimizer.walker.MultiChildStep`, and `org.brackit.server.xquery.compiler.translator.DBTranslator`.

Hint: For development and understanding what is going on it is usually best to visualize the AST. It Therefore you need to set `XQuery.DEBUG` to true, ideally via the prop `org.brackit.xquery.debug` config.properties. If set, the compiler will output the AST as renderable [GraphViz](https://www.graphviz.org/) dot files to `org.brackit.xquery.debugDir` (default is _.\/debug_).

Happy coding!

**Comment by JohannesLichtenberger** [comment]
Thanks so much, Sebastian. I already copied your BrackitDB examples a few years ago I think

https://github.com/sirixdb/sirix/tree/master/bundles/sirix-xquery/src/main/java/org/sirix/xquery/compiler

I also implemented Name-/Path- and CAS-Indexes back then, so I'll give it a try but maybe first add the native storage of JSON nodes to Sirix :-)

Do you by the way know if the work on the map reduce stuff had been released? :-)

**Comment by JohannesLichtenberger** [comment]
Hi Sebastian,

I feel a bit sorry to bother you again, and don't know if you'll read it, but as I nearly finished the JSON stuff (still missing a Brackit binding for now) do you know good literature about how to build a cost-based optimizer? From the CockroachDB guys I just read a blog entry that they began with an heuristics based optimizer, but it quickly went too complex and they developed a cost-based optimizer.

Best regards
Johannes

**Comment by sebbae** [comment]
Hey Johannes,

I don't have specific papers at hand, but I suppose the dissertation of one former from my old research groups references a great selection of references on the topic of cost-based optimization ;-)

[http://wwwlgis.informatik.uni-kl.de/cms/fileadmin/publications/2011/PhD-Dissertation-Weiner.pdf](http://wwwlgis.informatik.uni-kl.de/cms/fileadmin/publications/2011/PhD-Dissertation-Weiner.pdf)

**Comment by JohannesLichtenberger** [comment]
Thank you, Sebastian :-)
